################ English language ##################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ German language ##################
[de]
disabled = true
languageName = "DE"
languageCode = "de-DE"
contentDir = "content/german"
weight = 2
