############# German navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Artikel"
url = "blog/"
weight = 2

[[main]]
name = "Über mich"
url = "about/"
weight = 3

[[footer]]
name = "Über mich"
url = "about/"
weight = 1

[[footer]]
name = "Impressum"
url = "imprint/"
weight = 2

[[footer]]
name = "Datenschutz"
url = "privacy-policy/"
weight = 3
